---
- hosts: all
  become: yes
  tasks:
  - name: install apache on ubuntu
    apt:
      name: git
      state: present
    when: ansible_os_family == 'Debian'
  - name: install httpd on redhat
    yum:
      name: git
      state: present
    when: ansible_os_family == 'RedHat'
