---
# tasks file for common
- name: update packages on ubuntu
  command: apt-get update
  when: ansible_os_family == "Debian"
- name: update packages 0n Redhat
  command: yum update
  when: ansible_os_family == "RedHat"  


