---
- hosts: unix
  tasks:
  - name : execute
    command: echo "helloworld"
    register: result
  - name: print result
    debug:
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
        
